# -*- coding: utf-8 -*-
"""colab_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPdoovhoDMONDwPyinEtfFvPJoGaOma9
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.cluster import DBSCAN, AgglomerativeClustering
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.decomposition import PCA

"""Importing Data"""

df  = pd.read_csv("Facebook_Marketplace_data.csv")



"""Question 1"""

x = df.iloc[:,:12].values

print(pd.DataFrame(x))

"""Preprocessing Data"""

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values =np.nan , strategy= "mean")
imputer.fit(x[:,3:])
x[:,3:] = imputer.transform(x[:,3:])
print(pd.DataFrame(x))

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
x = np.array(ct.fit_transform(x))
print(pd.DataFrame(x))

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x[:,6:] = sc.fit_transform(x[:,6:])
PRI = pd.DataFrame(x)
print(PRI)
x = np.delete(x,4,1)
x = np.delete(x,4,1)
print(pd.DataFrame(x))

"""Question 2

elbow methord
"""

from sklearn.cluster import KMeans
wcss=[]
for i in range(1,11):
    kmeans = KMeans(n_clusters=i,init="k-means++",random_state=42)
    kmeans.fit(x)
    wcss.append(kmeans.inertia_)
plt.plot(range(1,11),wcss)
plt.title("The elbow methord")
plt.xlabel("Number of clusters")
plt.ylabel("WCSS")
plt.show()

"""Question 3


K-Map clustering
"""

#2 is the optinomal no of clusters
kmeans = KMeans(n_clusters=2,init="k-means++",random_state=42)
y_pred = kmeans.fit_predict(x)
plt.scatter(x[y_pred == 0,0],x[y_pred == 0,4],s=100,c="red",label="Cluster 1")
plt.scatter(x[y_pred == 1,0],x[y_pred == 1,4],s=100,c="blue",label="Cluster 2")
plt.title("Response for Link")
plt.xlabel("Link(1 for a link/0 for non-link)")
plt.ylabel("No of Response")
plt.legend()
plt.show()

plt.scatter(x[y_pred == 0,1],x[y_pred == 0,4],s=100,c="red",label="Cluster 1")
plt.scatter(x[y_pred == 1,1],x[y_pred == 1,4],s=100,c="blue",label="Cluster 2")
plt.title("Response for Photo")
plt.xlabel("Photo(1 for a Photo/0 for non-Photo)")
plt.ylabel("No of Response")
plt.legend()
plt.show()

plt.scatter(x[y_pred == 0,2],x[y_pred == 0,4],s=100,c="red",label="Cluster 1")
plt.scatter(x[y_pred == 1,2],x[y_pred == 1,4],s=100,c="blue",label="Cluster 2")
plt.title("Response for Status")
plt.xlabel("Status(1 for a Status/0 for non-Status)")
plt.ylabel("No of Response")
plt.legend()
plt.show()

plt.scatter(x[y_pred == 0,3],x[y_pred == 0,4],s=100,c="red",label="Cluster 1")
plt.scatter(x[y_pred == 1,3],x[y_pred == 1,4],s=100,c="blue",label="Cluster 2")
plt.title("Response for Video")
plt.xlabel("Video(1 for a Video/0 for non-Video)")
plt.ylabel("No of Response")
plt.legend()
plt.show()

"""DBSCAN"""

dbscan = DBSCAN(eps=5, min_samples=3)
dbscan_labels = dbscan.fit_predict(x)

"""Gaussian Mixture model"""

gmm = GaussianMixture(n_components=2, random_state=42)
gmm_labels = gmm.fit_predict(x)

bic_values = []
k_range = range(1, 11)

for k in k_range:
    temp_gmm = GaussianMixture(n_components=k, random_state=42)
    temp_gmm.fit(x)
    bic_values.append(temp_gmm.bic(x))

# 3. Plotting the BIC curve
plt.figure(figsize=(10, 6))
plt.plot(k_range, bic_values, marker='o', color='purple')
plt.title("GMM BIC Score per Cluster (Lower is Better)")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("BIC Value")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

hierarchical = AgglomerativeClustering(n_clusters=2)
hierarchical_labels = hierarchical.fit_predict(x)

import matplotlib.pyplot as plt

# Initialize a dictionary to store the scores for the graph
performance_scores = {}

for name, labels in models.items():
    if name == "DBSCAN":
        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)

        if n_clusters > 1:
            mask = labels != -1
            score = silhouette_score(x[mask], labels[mask])
            # Store the score in the dictionary
            performance_scores[name] = score
            print(f"{name} Silhouette Score (excluding noise): {score:.4f}")
        else:
            # Assign 0 if the model couldn't find enough clusters
            performance_scores[name] = 0
            print(f"{name}: Not enough clusters found.")
    else:
        score = silhouette_score(x, labels)
        # Store the score in the dictionary
        performance_scores[name] = score
        print(f"{name} Silhouette Score: {score:.4f}")

# --- Create the Bar Graph ---
plt.figure(figsize=(10, 6))
# Pass the dictionary keys as X and values as Y
plt.bar(performance_scores.keys(), performance_scores.values(), color=['red', 'blue', 'green', 'purple'])

plt.xlabel("Clustering Models")
plt.ylabel("Silhouette Score")
plt.title("Model Performance Comparison (Facebook Marketplace Analysis)")
plt.ylim(0, 1) # Sets the range from 0 to 1 for clarity
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

def plot_media_response(labels, model_name, media_col_idx, media_name):
    # media_col_idx: 0=Link, 1=Photo, 2=Status, 3=Video (based on your CT encoding)
    plt.figure(figsize=(8, 5))
    plt.scatter(x[labels == 0, media_col_idx], x[labels == 0, 4], s=100, c="red", label="Cluster 1")
    plt.scatter(x[labels == 1, media_col_idx], x[labels == 1, 4], s=100, c="blue", label="Cluster 2")
    plt.title(f"Response for {media_name} ({model_name})")
    plt.xlabel(f"{media_name} (1=Yes / 0=No)")
    plt.ylabel("No of Response")
    plt.legend()
    plt.show()

plot_media_response(hierarchical_labels, "Hierarchical", 3, "Video")
plot_media_response(hierarchical_labels, "Hierarchical", 2, "Photo")
plot_media_response(hierarchical_labels, "Hierarchical", 1, "Status")
plot_media_response(hierarchical_labels, "Hierarchical", 0, "Link")
plot_media_response(dbscan_labels, "DBSCAN", 3, "Video")
plot_media_response(dbscan_labels, "DBSCAN", 2, "Photo")
plot_media_response(dbscan_labels, "DBSCAN", 1, "Status")
plot_media_response(dbscan_labels, "DBSCAN", 0, "Link")

# Assuming your labels are in 'y_pred' (K-Means) or 'hierarchical_labels'
import pandas as pd

# If using K-Means
print("K-Means Cluster Counts:")
print(pd.Series(y_pred).value_counts())

# If using Hierarchical
print("\nHierarchical Cluster Counts:")
print(pd.Series(hierarchical_labels).value_counts())

print("\nDBSCAN Cluster Counts:")
print(pd.Series(dbscan_labels).value_counts())

# Assuming 'df' is your original dataframe from the CSV
# and 'y_pred', 'hierarchical_labels', and 'dbscan_labels' are your results

# 1. Add the "Bookmarks" (Labels) to the "Book" (Data)
df['KMeans_Cluster'] = y_pred
df['Hierarchical_Cluster'] = hierarchical_labels
df['DBSCAN_Cluster'] = dbscan_labels

# 2. Create the "Leaderboard" of High-Performance Groups
# We calculate the average reactions for the "Small" (Elite) group in each model
leaderboard_data = {
    "Model": ["K-Means (Cluster 0)", "Hierarchical (Cluster 0)", "DBSCAN (Cluster 0)"],
    "Avg Reactions": [
        df[df['KMeans_Cluster'] == 0]['num_reactions'].mean(),
        df[df['Hierarchical_Cluster'] == 0]['num_reactions'].mean(),
        df[df['DBSCAN_Cluster'] == 0]['num_reactions'].mean()
    ],
    "Group Size": [6761, 6945,7018 ] # Using the counts we found earlier
}

import pandas as pd
leaderboard_df = pd.DataFrame(leaderboard_data)
print(leaderboard_df.sort_values(by="Avg Reactions", ascending=False))

# 1. Calculate the Baseline (Cluster 0 across all models is roughly the same)
base_avg = df[df['KMeans_Cluster'] == 0]['num_reactions'].mean()

# 2. Calculate Averages for the "Elite" Groups
km_avg = df[df['KMeans_Cluster'] == 1]['num_reactions'].mean()
hi_avg = df[df['Hierarchical_Cluster'] == 1]['num_reactions'].mean()
db_avg = df[df['DBSCAN_Cluster'] == -1]['num_reactions'].mean()

# 3. Calculate the Engagement Multiplier (The Gap)
km_gap = km_avg / base_avg
hi_gap = hi_avg / base_avg
db_gap = db_avg / base_avg

print(f"Baseline Average: {base_avg:.2f} reactions\n")
print(f"K-Means Elite: {km_avg:.2f} reactions ({km_gap:.1f}x better)")
print(f"Hierarchical Elite: {hi_avg:.2f} reactions ({hi_gap:.1f}x better)")
print(f"DBSCAN Viral: {db_avg:.2f} reactions ({db_gap:.1f}x better)")

# 1. Define all metrics we want to track
metrics = ['num_reactions', 'num_comments', 'num_shares', 'num_likes']

media_types = ['video', 'photo', 'link', 'status']

def generate_multiplier_table(df, medium_name):
    medium_df = df[df['status_type'] == medium_name].copy()

    model_configs = [

        ('DBSCAN', 'DBSCAN_Cluster')
    ]

    final_rows = []

    for model_name, col_name in model_configs:
        # Calculate means for each cluster in this model
        cluster_means = medium_df.groupby(col_name)[metrics].mean()

        # Determine the "Base Condition" (Minimum mean for each metric within this model)
        base_conditions = cluster_means.min()

        for cluster in sorted(medium_df[col_name].unique()):
            group_label = "Outlier (-1)" if (model_name == "DBSCAN" and cluster == -1) else f"Cluster {cluster}"
            row_data = {
                'Model': model_name,
                'Group': group_label,
                'Count': len(medium_df[medium_df[col_name] == cluster])
            }

            # Calculate Value and Multiplier for each metric
            for m in metrics:
                current_val = cluster_means.loc[cluster, m]
                base_val = base_conditions[m]

                # Calculate Multiplier (handle division by zero if base is 0)
                multiplier = (current_val / base_val) if base_val > 0 else 1.0

                display_name = m.replace('num_', '').capitalize()
                row_data[f'{display_name}'] = round(current_val, 2)
                row_data[f'{display_name} (x)'] = f"{multiplier:.1f}x"

            final_rows.append(row_data)

    return pd.DataFrame(final_rows)

# Generate and display the 4 tables
for medium in media_types:
    print(f"\n{'='*40} {medium.upper()} STRATEGY TABLE {'='*40}")
    table = generate_multiplier_table(df, medium)
    # Use display() in Colab to show the full wide table
    display(table)